Repository Drewbi/startify, pull requests merged in 2020-06, with the labels that each got.

#3 Set up basic project
  .eslintrc.js
  .gitignore
  .prettierrc.js
  README.md
  next-env.d.ts
  package.json
  pages/index.tsx
  public/favicon.ico
  public/vercel.svg
  tsconfig.json
  yarn.lock
Labels: review needed

#10 readme Update
  README.md
Labels: documentation, enhancement

#8 Extra .gitignore entries
  .gitignore
Labels: enhancement

#19 Added state management control
  components/FakeContext.tsx
  components/Test.tsx
  pages/_app.tsx
  pages/home.tsx
Labels: enhancement

#26 Component and styling
  assets/style/globalStyle.js
  components/CallToAction/index.tsx
  components/FirstRow/index.tsx
  components/Footer.tsx
  components/Header.tsx
  components/Hero.tsx
  components/Logo.tsx
  components/Products.tsx
  components/Products/Card.tsx
  components/Products/index.tsx
  components/SecondRow/Card.tsx
  components/SecondRow/index.tsx
  components/TagLine/index.tsx
  components/ThirdRow/index.tsx
  components/index.tsx
  pages/_app.tsx
  pages/home/[seed].tsx
  public/bear.svg
  public/notes.svg
  public/stats.svg
Labels: enhancement, review needed

#24 Add faker data generation function
  assets/PhraseData.ts
  core/faker.ts
  package.json
  pages/api/fake.ts
  yarn.lock
Labels: enhancement

#23 Added source svg files
  assets/illustrations/undraw_access_account_99n5.svg
  assets/illustrations/undraw_attached_file_n4wm.svg
  assets/illustrations/undraw_bear_market_ania.svg
  assets/illustrations/undraw_build_wireframe_u9m2.svg
  assets/illustrations/undraw_code_inspection_bdl7.svg
  assets/illustrations/undraw_cohort_analysis_stny.svg
  assets/illustrations/undraw_collaborators_prrw.svg
  assets/illustrations/undraw_conceptual_idea_xw7k.svg
  assets/illustrations/undraw_contract_uy56.svg
  assets/illustrations/undraw_crypto_portfolio_2jy5.svg
  assets/illustrations/undraw_data_extraction_ih3n.svg
  assets/illustrations/undraw_data_processing_yrrv.svg
  assets/illustrations/undraw_data_reports_706v.svg
  assets/illustrations/undraw_design_notes_8dmv.svg
  assets/illustrations/undraw_develop_app_kvt2.svg
  assets/illustrations/undraw_download_files_aydf.svg
  assets/illustrations/undraw_drone_surveillance_kjjg.svg
  assets/illustrations/undraw_file_analysis_8k9b.svg
  assets/illustrations/undraw_grid_design_obmd.svg
  assets/illustrations/undraw_investment_data_yfvt.svg
  assets/illustrations/undraw_job_offers_kw5d.svg
  assets/illustrations/undraw_mobile_development_8gyo.svg
  assets/illustrations/undraw_mobile_encryption_cl5q.svg
  assets/illustrations/undraw_mobile_feed_73bd.svg
  assets/illustrations/undraw_mobile_posts_tlwg.svg
  assets/illustrations/undraw_mobile_wireframe_euf4.svg
  assets/illustrations/undraw_my_documents_ym8x.svg
  assets/illustrations/undraw_nakamoto_2iv6.svg
  assets/illustrations/undraw_new_entries_nh3h.svg
  assets/illustrations/undraw_next_js_8g5m.svg
  assets/illustrations/undraw_online_collaboration_7pfp.svg
  assets/illustrations/undraw_online_connection_6778.svg
  assets/illustrations/undraw_online_information_4ui6.svg
  assets/illustrations/undraw_online_messaging_9ro6.svg
  assets/illustrations/undraw_performance_overview_p9bm.svg
  assets/illustrations/undraw_pitching_36ol.svg
  assets/illustrations/undraw_product_iteration_kjok.svg
  assets/illustrations/undraw_progress_data_4ebj.svg
  assets/illustrations/undraw_progress_indicator_p84k.svg
  assets/illustrations/undraw_proud_coder_7ain.svg
  assets/illustrations/undraw_publish_article_icso.svg
  assets/illustrations/undraw_redesign_feedback_48ti.svg
  assets/illustrations/undraw_reviewed_docs_neeb.svg
  assets/illustrations/undraw_server_cluster_jwwq.svg
  assets/illustrations/undraw_spreadsheet_69ax.svg
  assets/illustrations/undraw_statistic_chart_38b6.svg
  assets/illustrations/undraw_stock_prices_afrt.svg
  assets/illustrations/undraw_sync_files_xb3r.svg
  assets/illustrations/undraw_the_world_is_mine_nb0e.svg
  assets/illustrations/undraw_updated_resume_u4fy.svg
  assets/illustrations/undraw_web_search_eetr.svg
  assets/illustrations/undraw_work_together_h63l.svg
  components/Illustration.tsx
  components/Test.tsx
Labels: enhancement, review needed

#33 Changed to faker generated number
  core/faker.ts
Labels: bug

#37 Fixed menu css
  assets/style/globalStyle.js
  pages/index.tsx
  public/bear.svg
  public/notes.svg
  public/stats.svg
  public/undraw_code_inspection_bdl7.svg
  public/undraw_statistic_chart_38b6.svg
  public/undraw_updated_resume_u4fy.svg
  public/vercel.svg
Labels: design
